languageCode = "en"
languageName = "English"
weight = 1
title = "0xLaurens.com"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = " "
dateFormat = "2 January 2006"


[[params.author.links]]
github = "https://github.com/0xlaurens/"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/laurens-w/"

[[params.author.links]]
email = "mailto:laurens.weterings@gmail.com"

[author]
name = "Laurens Weterings"
bio = "Software Developer & Student"

  [[author.links]]
  github = "https://github.com/0xlaurens/"

  [[author.links]]
  linkedin = "https://linkedin.com/in/laurens-w"

  [[author.links]]
  email = "mailto:laurens.weterings@gmail.com"

["params.author"]
name = "Laurens Weterings"
image = "profile-2026.jpg"