languageCode = "en"
languageName = "English"
weight = 1
title = "0xLaurens.com"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = " "
dateFormat = "2 January 2006"

[author]
name = "Laurens Weterings"
image = "img/avatar.png"
headline = " "
bio = "A little bit about you"
links = []
