colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = false
enableCodeCopy = true
mainSections = [ "posts" ]
defaultBackgroundImage = "q"

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = false 
showAppearanceSwitcher = true
showScrollToTop = true
showMenu = true 

[homepage]
layout = "profile"
showRecent = false 
showRecentItems = "0"
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = ""

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true
heroStyle = "background"

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]

[term]
heroStyle = "big"
