[build]
plan = "hugo"

[plan.hugo]
src = "."
output = "public"
build_cmd = "hugo --minify --gc"

[plan.hugo.packages]
packages = ["hugo"]

[plan.hugo.hooks]
post_build = "echo 'build finished'"

[run]
command = "hugo server --bind=0.0.0.0 --port=$PORT"

[static]
dir = "public"

[variables]
PORT = "3000"
